### ISSUE TITLE
allow tracking per-project config in CLI

### ISSUE THREAD

**Issue by scarmuega** [demeter-run/cli#13]
DoD:

- [ ] we have a `projects add <id>` command in the cli
- [ ] the command asks for an API KEY that needs to be entered manually (similar to a password)
- [ ] we persists config (id, api key) in the local filesystem of the user
